---
version: "3.8"
services:
  movies:
    image: baburaogurana/mmovies:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: baburaogurana/train:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: baburaogurana/recharge:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: baburaogurana/dth:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
